### ISSUE TITLE
Chassis v2 svg Mirobot logo increases file size and increases cutting time

### ISSUE THREAD

**Issue by mcarne** [mirobot/mirobot-chassis#5]
I suggest to change the logo type on the Chassis. The current logo increases the file size 20 times from 25k to 500k.
Furthermore the current logo takes long to print thus increases the cost of cutting the parts considerably. Should be changed to a logo / brand name that is faster to print.

**Comment by bjpirt** [comment]
How did you etch this part? It would take a long time if you cut each piece of the logo as an outline, but if you etched it it would take the same time as any other logo since it just scans back and forth. As this is the same as the production Mirobot I'm leaving it as-is, but you're welcome to change it if you feel the urge
